#! /bin/sh

killall -9 sxhkd xsettingsd compton
sxhkd &
xsettingsd &
feh --bg-fill $HOME/Pictures/Wallpapers/72055179_p0.jpg &
#sh /home/bwaiwnl/.screenlayout/dmon.sh &
compton --config ~/.config/compton/config &
sh $HOME/.config/polybar/launch.sh &
mpd &
exec nm-applet &
if [ -f /usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 ] ; then
    /usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &
fi

#bspc monitor VGA-1 -d I II III IV V
#bspc monitor LVDS-1 -d VI VII VIII IX X
bspc monitor LVDS -d 一 二 三 四 五
bspc monitor VGA-0 -d 六 七 八 九 十

# Width border
bspc config border_width         3

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config paddingless_monocle true
bspc config single_monocle false

# Gap
bspc config window_gap          8
bspc config top_padding 32
bspc config right_padding 8
bspc config bottom_padding 8
bspc config left_padding 8
#bspc config focus_follows_pointer true
bspc rule -a Gimp desktop='^8' state=floating follow=on


# Colors
base00="#282936"
base01="#3a3c4e"
base02="#4d4f68"
#base03="#bd93f9"
base03="#626483"
base04="#62d6e8"
base05="#e9e9f4"
base06="#f1f2f8"
base07="#f7f7fb"
base08="#ea51b2"
base09="#b45bcf"
base0A="#00f769"
base0B="#ebff87"
base0C="#a1efe4"
base0D="#62d6e8"
base0E="#b45bcf"
base0F="#00f769"


bspc config normal_border_color $base00
bspc config focused_border_color $base08
bspc config presel_border_color '#d79921'
bspc config normal_sticky_border_color '#4e4e4e'
bspc config focused_sticky_border_color '#83a598'
bspc config urgent_border_color $base08
